apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: imtiaz-pubsub
spec:
  type: pubsub.kafka
  version: v1
  metadata:
  - name: brokers
    value: "kafka:29092"
  - name: consumerGroup
    value: "product-service-group"
  - name: clientId
    value: "product-service"
  - name: authType
    value: "none"
