# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: product_events.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'product_events.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14product_events.proto\x12\x07product\"\x95\x01\n\x0eProductCreated\x12\x12\n\nproduct_id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x01\x12\x16\n\x0estock_quantity\x18\x05 \x01(\x05\x12\x11\n\tis_active\x18\x06 \x01(\x08\x12\x12\n\ncreated_at\x18\x07 \x01(\t\"\x95\x01\n\x0eProductUpdated\x12\x12\n\nproduct_id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x01\x12\x16\n\x0estock_quantity\x18\x05 \x01(\x05\x12\x11\n\tis_active\x18\x06 \x01(\x08\x12\x12\n\nupdated_at\x18\x07 \x01(\t\"V\n\x0eProductDeleted\x12\x12\n\nproduct_id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x12\n\ndeleted_at\x18\x03 \x01(\t\x12\x0e\n\x06reason\x18\x04 \x01(\t\"v\n\x0cStockChanged\x12\x12\n\nproduct_id\x18\x01 \x01(\x05\x12\x14\n\x0cold_quantity\x18\x02 \x01(\x05\x12\x14\n\x0cnew_quantity\x18\x03 \x01(\x05\x12\x12\n\nchanged_at\x18\x04 \x01(\t\x12\x12\n\nchanged_by\x18\x05 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'product_events_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRODUCTCREATED']._serialized_start=34
  _globals['_PRODUCTCREATED']._serialized_end=183
  _globals['_PRODUCTUPDATED']._serialized_start=186
  _globals['_PRODUCTUPDATED']._serialized_end=335
  _globals['_PRODUCTDELETED']._serialized_start=337
  _globals['_PRODUCTDELETED']._serialized_end=423
  _globals['_STOCKCHANGED']._serialized_start=425
  _globals['_STOCKCHANGED']._serialized_end=543
# @@protoc_insertion_point(module_scope)
