# tests/unit/test_repositories_product.py

import pytest
from unittest.mock import Mock, patch, MagicMock
from sqlmodel import Session, select
from app.models.product import ProductModel
from app.repositories.product_repo import ProductRepository
from datetime import datetime, timezone
import uuid

class TestProductRepository:

    @pytest.fixture
    def mock_session(self):
        """Provides a mock SQLModel Session object."""
        return Mock(spec=Session)

    @pytest.fixture
    def product_repo(self, mock_session):
        """Provides a ProductRepository instance with a mocked session."""
        return ProductRepository(session=mock_session)

    def test_create_product(self, product_repo, mock_session):
        """
        Test that the create method correctly adds the product model
        to the session, commits, and refreshes the instance.
        """
        # Given: A domain product object (or data to create a ProductModel)
        # For this unit test, we'll directly test the repository's interaction
        # with the session using a ProductModel instance.
        # In a real scenario, the service layer might convert a domain object to this.
        product_name = "Test Product"
        product_description = "A product for testing"
        product_price = 10.99
        product_category_id = str(uuid.uuid4()) # Assume a valid category ID exists
        product_brand = "Test Brand"
        product_tags = "tag1,tag2"
        product_image_url = "http://example.com/image.jpg"

        # Create the ProductModel instance that the repo will handle
        # Note: created_at/updated_at will be set by SQLModel defaults or manually in repo if needed
        # For this test, we'll focus on the session calls.
        product_model_to_create = ProductModel(
            name=product_name,
            description=product_description,
            price=product_price,
            category_id=product_category_id,
            brand=product_brand,
            tags=product_tags,
            image_url=product_image_url,
            # is_active defaults to True
            # created_at and updated_at will be set by SQLModel defaults or repo logic
        )

        # Mock the return value of session.refresh to simulate the DB setting ID/timestamps
        # refresh doesn't typically return the object, it modifies it in place
        # We just need to ensure it's called.
        # Let's give the model an ID *after* the session.add is conceptually called,
        # which happens inside the repo's create method.
        # Mocking session.add, session.commit, session.refresh
        mock_session.add.return_value = None # add doesn't return anything
        mock_session.commit.return_value = None # commit doesn't return anything
        # session.refresh also doesn't return anything, it modifies the object in place
        mock_session.refresh.side_effect = lambda obj: setattr(obj, 'id', str(uuid.uuid4())) or setattr(obj, 'created_at', datetime.now(timezone.utc)) or setattr(obj, 'updated_at', datetime.now(timezone.utc))

        # When: Calling the repository's create method
        returned_product_model = product_repo.create(product_model_to_create)

        # Then: Verify the session methods were called correctly
        # 1. session.add was called with the product model instance
        mock_session.add.assert_called_once_with(product_model_to_create)

        # 2. session.commit was called once after adding
        mock_session.commit.assert_called_once()

        # 3. session.refresh was called once on the product model instance
        # to update it with the ID and timestamps generated by the DB
        mock_session.refresh.assert_called_once_with(product_model_to_create)

        # 4. The returned object should be the same instance passed to add/commit/refresh
        # and should now have an ID and timestamps (as simulated by the side_effect)
        assert returned_product_model is product_model_to_create
        assert returned_product_model.id is not None # Should be set by refresh or SQLModel default
        assert returned_product_model.created_at is not None
        assert returned_product_model.updated_at is not None

# Example of a test for get_by_id (using Mock Session.get)
# def test_get_product_by_id(self, product_repo, mock_session):
#     # Given
#     product_id = "some-uuid-string"
#     expected_product = ProductModel(id=product_id, name="Fetched Product", ...) # Fill in other fields
#     mock_session.get.return_value = expected_product
#
#     # When
#     result = product_repo.get_by_id(product_id)
#
#     # Then
#     mock_session.get.assert_called_once_with(ProductModel, product_id)
#     assert result == expected_product
#
# Example of a test for list_all (using Mock Session.exec)
# def test_list_all_products(self, product_repo, mock_session):
#     # Given
#     expected_products = [
#         ProductModel(id=str(uuid.uuid4()), name="Product 1", ...),
#         ProductModel(id=str(uuid.uuid4()), name="Product 2", ...),
#     ]
#     mock_exec_result = Mock()
#     mock_exec_result.all.return_value = expected_products
#     mock_session.exec.return_value = mock_exec_result
#
#     # When
#     results = product_repo.list_all()
#
#     # Then
#     # Check that exec was called with the correct select statement
#     # mock_session.exec.assert_called_once() # This is harder to assert precisely without mocking select itself
#     # A more robust way might involve checking the type of the argument passed to exec
#     # stmt = mock_session.exec.call_args[0][0] # Get the first argument (the statement)
#     # assert isinstance(stmt, Select) # Check it's a Select object
#     # # Further checks on the select object could be done if needed
#     assert results == expected_products
